import { Inter } from "next/font/google";
import "./globals.css";
import NabBar from "./Components/NavBar/NabBar";
import Footer from "./Components/Footer/Footer";
import HeroSection from "./Components/HeroSection/HeroSection";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-heroBG min-h-[100vh] bg-[#062630] px-4 bg-cover from-transparent pb-14">
          <div className="max-w-7xl mx-auto">
            <NabBar />
            <HeroSection />
          </div>
        </div>
        {children}
        <Footer />
      </body>
    </html>
  );
}
